# Generated by Django 5.2.3 on 2025-06-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='news_images/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
