# Generated by Django 5.2.3 on 2025-06-21 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_newsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
